version: '3.8'

services:
  web:
    build: .
    command: gunicorn Diploma.wsgi:application --bind 0.0.0.0:8000
    expose:
    - 8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  static_volume:
  media_volume:
  postgres_data: