version: '3.8'

services:
  web:
    build: .
    command: gunicorn Diploma.wsgi:application --bind 0.0.0.0:8000
    expose:
    - 8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data: