# Generated by Django 5.0.3 on 2024-04-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_collection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to='non-converted/'),
        ),
    ]
