# Generated by Django 5.0.4 on 2024-05-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_collection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(blank=True, choices=[('t', 'Top'), ('s', 'Side')], max_length=1, null=True)),
                ('health_status', models.CharField(blank=True, choices=[('s', 'Sick'), ('h', 'Healthy')], max_length=1, null=True)),
                ('sickness', models.CharField(blank=True, choices=[('artritus', 'Artritus'), ('bursitus', 'Bursitus'), ('necroz', 'Necroz'), ('oasteoartritus', 'Oasteoartritus'), ('phz', 'Phz'), ('revma_arthritus', 'Revma_arthritus'), ('rozryv_meniska', 'rozryv_meniska'), ('tenditit', 'Tenditit')], max_length=20, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.collection')),
            ],
        ),
    ]
