# Generated by Django 5.0.4 on 2024-05-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_collectionstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionstats',
            name='health_status',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('healthy', 'Healthy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collectionstats',
            name='image_type',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('side', 'Side')], max_length=10, null=True),
        ),
    ]
