# Generated by Django 5.0.3 on 2024-04-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio_compatibility', models.IntegerField(verbose_name='Біосумісність')),
                ('strength_durability', models.IntegerField(verbose_name='Міцність і довговічність')),
                ('wear_resistance', models.IntegerField(verbose_name='Зносостійкість')),
                ('elasticity_modulus', models.IntegerField(verbose_name='Модуль пружності')),
                ('corrosion_resistance', models.IntegerField(verbose_name='Стійкість до корозії')),
                ('material_component', models.ManyToManyField(related_name='components', to='material_selector.materialcomponent')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material_selector.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('material1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material1', to='material_selector.material')),
                ('material2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material2', to='material_selector.material')),
            ],
        ),
    ]
