# Generated by Django 5.0.3 on 2024-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_selector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_component',
            field=models.ManyToManyField(related_name='materials', to='material_selector.materialcomponent'),
        ),
    ]
